// src/pages/StaffDashboard.jsx
import { useEffect, useState, useCallback } from 'react';
import { api, setAuthToken } from '../lib/api';
import DataTable from 'react-data-table-component';
import {
  FaDownload,
  FaFilePdf,
  FaLink,
  FaSearch
} from 'react-icons/fa';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useNavigate } from 'react-router-dom';
import Swal from 'sweetalert2';

export default function StaffDashboard() {
  const navigate = useNavigate();
  const [submissions, setSubmissions] = useState([]);
  const [filteredSubs, setFilteredSubs] = useState([]);
  const [links, setLinks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const BACKEND_URL =
    import.meta.env.VITE_BACKEND_URL ||
    'https://fibuca-backend.vercel.app';

  /* ================= AUTH & FETCH ================= */
  useEffect(() => {
    const user =
      JSON.parse(localStorage.getItem('fibuca_user')) ||
      JSON.parse(sessionStorage.getItem('fibuca_user'));

    const token =
      localStorage.getItem('fibuca_token') ||
      sessionStorage.getItem('fibuca_token');

    if (!user || (user.role !== 'STAFF' && user.role !== 'ADMIN')) {
      navigate('/login');
      return;
    }

    if (token) setAuthToken(token);

    fetchSubmissions();
    fetchLinks();
  }, [navigate]);

  const fetchSubmissions = useCallback(() => {
    setLoading(true);
    api.get('/staff/submissions') // returns submissions for logged-in staff
      .then(res => {
        setSubmissions(res.data);
        setFilteredSubs(res.data);
      })
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  const fetchLinks = () => {
    api.get('/staff/links') // returns links generated by staff
      .then(res => setLinks(res.data))
      .catch(err => console.error(err));
  };

  /* ================= SEARCH ================= */
  const handleSearch = value => {
    if (!value) return setFilteredSubs(submissions);

    const results = submissions.filter(s =>
      (s.employeeName || '').toLowerCase().includes(value.toLowerCase()) ||
      (s.employeeNumber || '').toLowerCase().includes(value.toLowerCase()) ||
      (s.employerName || '').toLowerCase().includes(value.toLowerCase())
    );

    setFilteredSubs(results);
  };

  /* ================= EXPORT ================= */
  const exportToExcel = () => {
    if (!filteredSubs.length)
      return Swal.fire('No Data', 'No records found.', 'info');

    const data = filteredSubs.map((s, index) => ({
      SN: index + 1,
      Name: s.employeeName,
      Number: s.employeeNumber,
      Employer: s.employerName,
      Dues: s.dues,
      Submitted: s.submittedAt
        ? new Date(s.submittedAt).toLocaleString()
        : ''
    }));

    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Submissions');
    XLSX.writeFile(workbook, 'staff_submissions.xlsx');
  };

  const exportToPDF = () => {
    if (!filteredSubs.length)
      return Swal.fire('No Data', 'No records found.', 'info');

    const doc = new jsPDF();
    autoTable(doc, {
      head: [['SN', 'Name', 'Number', 'Employer', 'Dues', 'Submitted']],
      body: filteredSubs.map((s, index) => [
        index + 1,
        s.employeeName,
        s.employeeNumber,
        s.employerName,
        s.dues,
        s.submittedAt ? new Date(s.submittedAt).toLocaleString() : ''
      ])
    });
    doc.save('staff_submissions.pdf');
  };

  /* ================= GENERATE LINK ================= */
  const handleGenerateLink = async () => {
    setGenerating(true);
    try {
      const { value: formValues } = await Swal.fire({
        title: 'Generate Link',
        html:
          '<input id="swal-hours" class="swal2-input" placeholder="Hours valid" type="number">' +
          '<input id="swal-max" class="swal2-input" placeholder="Max uses (optional)" type="number">',
        focusConfirm: false,
        preConfirm: () => ({
          hoursValid: parseInt(document.getElementById('swal-hours').value) || 24,
          maxUses: parseInt(document.getElementById('swal-max').value) || null
        })
      });

      if (!formValues) return;

      const res = await api.post('/staff/generate-link', formValues);
      Swal.fire('Link Generated', `<a href="${res.data.link}" target="_blank">${res.data.link}</a>`, 'success');
      fetchLinks();
    } catch (err) {
      console.error(err);
      Swal.fire('Error', 'Failed to generate link.', 'error');
    } finally {
      setGenerating(false);
    }
  };

  /* ================= TABLE COLUMNS ================= */
  const columns = [
    { name: '#', selector: (row, i) => i + 1, width: '60px' },
    { name: 'Employee', selector: r => r.employeeName, sortable: true, wrap: true },
    { name: 'Number', selector: r => r.employeeNumber, wrap: true },
    { name: 'Employer', selector: r => r.employerName, wrap: true },
    { name: 'Dues', selector: r => r.dues },
    {
      name: 'PDF',
      cell: row => {
        if (!row.pdfPath) return <span className="text-gray-400">None</span>;
        const pdfUrl = row.pdfPath.startsWith('http') ? row.pdfPath : `${BACKEND_URL}/${row.pdfPath}`;
        return <a href={pdfUrl} target="_blank" rel="noopener noreferrer" className="text-red-600 hover:underline"><FaFilePdf /></a>;
      }
    }
  ];

  /* ================= LINKS TABLE ================= */
  const linkColumns = [
    { name: '#', selector: (row, i) => i + 1, width: '60px' },
    { name: 'Link', selector: row => row.token, wrap: true, cell: row => <a href={`${process.env.FRONTEND_URL}/submission/${row.token}`} target="_blank" className="text-blue-600 hover:underline">{row.token}</a> },
    { name: 'Max Uses', selector: row => row.maxUses || 'Unlimited' },
    { name: 'Used', selector: row => row.usedCount },
    { name: 'Expires At', selector: row => new Date(row.expiresAt).toLocaleString() },
    { name: 'Active', selector: row => row.isActive ? 'Yes' : 'No' }
  ];

  /* ================= UI ================= */
  return (
    <div className="min-h-screen bg-gray-100 p-4 md:p-8">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between gap-4">
          <h1 className="text-3xl font-bold text-gray-800">Staff Dashboard</h1>
          <div className="relative w-full md:w-72">
            <FaSearch className="absolute top-3 left-3 text-gray-400" />
            <input
              type="text"
              placeholder="Search submissions..."
              onChange={e => handleSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border rounded-lg shadow-sm focus:ring-2 focus:ring-blue-500 outline-none"
            />
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <button
            onClick={handleGenerateLink}
            disabled={generating}
            className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition"
          >
            <FaLink className="inline mr-2" /> {generating ? 'Generating...' : 'Generate Link'}
          </button>
          <button
            onClick={exportToExcel}
            className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition"
          >
            <FaDownload className="inline mr-2" /> Excel
          </button>
          <button
            onClick={exportToPDF}
            className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition"
          >
            <FaFilePdf className="inline mr-2" /> PDF
          </button>
        </div>

        {/* Submissions Table */}
        <div className="bg-white rounded-xl shadow-lg overflow-hidden">
          <DataTable
            columns={columns}
            data={filteredSubs}
            pagination
            progressPending={loading}
            highlightOnHover
            responsive
            striped
          />
        </div>

        {/* Generated Links Table */}
        <div className="bg-white rounded-xl shadow-lg overflow-hidden mt-6">
          <h2 className="text-xl font-bold p-4 border-b">Generated Links</h2>
          <DataTable
            columns={linkColumns}
            data={links}
            pagination
            highlightOnHover
            responsive
            striped
          />
        </div>
      </div>
    </div>
  );
}